### ISSUE TITLE
Nagios doesn't start if no services are defined

### ISSUE THREAD

**Issue by tas50** [schubergphilis/nagios#264]
Now that the server doesn't check itself there can exist a condition where no services are defined and the service will fail to start.  It might make sense to define a bogus service is the service array is empty.

**Comment by juliandunn** [comment]
+1, just hit this myself... could even throw in a totally bogus service unconditionally just so Nagios will start.

**Comment by kkdk5535** [comment]
We throw a host and service based on localhost with check dummy command. It should be conditional and can be done easily dropped in place by via cookbook_file resource

**Comment by tas50** [comment]
The original design of the cookbook came preloaded with some base checks.  There was a lot of pushback from that since everyone wants to monitor their environment differently.  In one of the later versions I removed all the out of box checks, which is what led to this issue.  I'm open to a service def / check that would function w/o any other servers present (nagios being server one in your environment), and without NRPE installed on the host.

**Comment by sbotman** [comment]
Old ticket which is open way to long, sorry about that. But think this whole issue is solved when we moved towards the new nagios configuration structure (cookbook version > 7.x)  by putting all objects within the Nagios.instance object model. If it's still an issue than please feel free to re-open the ticket, but I will close it for now.
