### ISSUE TITLE
Ubuntu 14.04 Apache installs fail due to CGI setup

### ISSUE THREAD

**Issue by tas50** [schubergphilis/nagios#327]
service apache2 reload
 * Reloading web server apache2                                                                              *
 * The apache2 configtest failed. Not doing anything.
Output of config test was:
[Wed Jan 21 18:17:56.562318 2015] [:crit] [pid 12384:tid 140013584004992] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
AH00013: Pre-configuration failed
Action 'configtest' failed.
The Apache error log may have more information.

**Comment by apsey** [comment]
Same issue here

**Comment by ChrisLundquist** [comment]
This changed in some newer version of apache2.
To go back to preforking:

```
a2dismod mpm_event
a2enmod mpm_prefork
service apache2 restart
```

Though this breaks each time chef runs because of the apache2 defaults for 14.04

In your role you can also specify [(apache recipe source)](https://github.com/svanzoest-cookbooks/apache2/blob/62d463d5e744e61ac5530f48a97e4f7bb4ac85ba/attributes/default.rb#L21-L42):

``` ruby
default['apache']['mpm'] = "worker'
```

If we include
[apache2::mpm_worker](https://github.com/svanzoest-cookbooks/apache2/blob/master/recipes/mpm_worker.rb)

This should do the needful.

**Comment by leoditommaso** [comment]
If you don't care about performance when using the web interface it is also possible to just set the following attribute in your role:

``` ruby
["apache"]["mpm"] = "prefork"
```

**Comment by ChrisLundquist** [comment]
Yeah, that's what I mentioned with:

> In your role you can also specify (apache recipe source):
> 
> default['apache']['mpm'] = "worker'

**Comment by sbotman** [comment]
@tas50 This ticket is also open for a while... could you please review it for us.

**Comment by tas50** [comment]
I'll take a look at this today. Sorry for the delay

**Comment by caussourd** [comment]
Hi! I got the same issue using the Nagios cookbook 7.1.8 but I then realized it had been fixed in the code. When will it be released to the Chef supermarket? Thanks

**Comment by sbotman** [comment]
Well, it just got merged and I have an open pull request that I would like to adjust and get merged before releasing a new release. But I'm free this week, so next week I will upload the new version to the supermarket... Or maybe somebody else will beat me to it, you never know ;)
